apiVersion: apps/v1

kind: Deployment

metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  template:
    metadata:
      name: mysql
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
            - containerPort: 33060
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
  replicas: 3
  selector:
    matchLabels:
      app: mysql
