pipeline {
    agent {dockerfile true}
    tools {
        maven '3.8.6'
    }
    
    stages {
        stage('SCM') {
          steps {
            checkout scm
          }
        }
        stage('Build') {
            steps {
                echo 'Build..'
            }
        }
        stage('Test') {
            steps {
                dir('scf-api') {
                  withSonarQubeEnv('SonarQube') {
                    sh 'mvn clean verify sonar:sonar -Dsonar.projectKey=scf-api'
                  }
                }
            }
        }
        stage('Deploy') {
            steps {
                sh 'node --version'
                sh 'svn --version'
            }
        }
    }
}