pipeline {
    agent any
    tools {
        maven '3.8.6'
    }
    
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean verify sonar:sonar -Dsonar.projectKey=poc-sistemas-controle-financas'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}