pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('SonarQube Analysis') {
		  def mvn = tool 'Default Maven';
		  withSonarQubeEnv() {
		    sh "${mvn}/bin/mvn clean verify sonar:sonar -Dsonar.projectKey=poc-sistemas-controle-financas"
		  }
		}
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}